version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the
# same dev machine.

services:

  parking-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5105:80"
